// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNw2ML9bDNkKwqOUuBT1yUZXdHjQMjzIY',
    appId: '1:570814061119:web:0f5c4cf87228a226b8f68a',
    messagingSenderId: '570814061119',
    projectId: 'azkari-app-83f34',
    authDomain: 'azkari-app-83f34.firebaseapp.com',
    storageBucket: 'azkari-app-83f34.firebasestorage.app',
    measurementId: 'G-N73KWVV37X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdmA4ycGXuA2oVk73xqbf7YQS23CTiwM0',
    appId: '1:570814061119:android:c4e13094bc48c902b8f68a',
    messagingSenderId: '570814061119',
    projectId: 'azkari-app-83f34',
    storageBucket: 'azkari-app-83f34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdDPjRNvamCNaVzT2Lg8J9fldXPI5-sXg',
    appId: '1:570814061119:ios:2f4c9a6be3b4c064b8f68a',
    messagingSenderId: '570814061119',
    projectId: 'azkari-app-83f34',
    storageBucket: 'azkari-app-83f34.firebasestorage.app',
    iosBundleId: 'com.example.azkariApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdDPjRNvamCNaVzT2Lg8J9fldXPI5-sXg',
    appId: '1:570814061119:ios:2f4c9a6be3b4c064b8f68a',
    messagingSenderId: '570814061119',
    projectId: 'azkari-app-83f34',
    storageBucket: 'azkari-app-83f34.firebasestorage.app',
    iosBundleId: 'com.example.azkariApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNw2ML9bDNkKwqOUuBT1yUZXdHjQMjzIY',
    appId: '1:570814061119:web:937af1a48383f05cb8f68a',
    messagingSenderId: '570814061119',
    projectId: 'azkari-app-83f34',
    authDomain: 'azkari-app-83f34.firebaseapp.com',
    storageBucket: 'azkari-app-83f34.firebasestorage.app',
    measurementId: 'G-JE307QQZ6B',
  );
}
